import pyvista as pv

def fence_axes(plotter,xlabel='PS_x (m)',ylabel='PS_y (m)',zlabel=' '):
    """
    % (C) Nick Holschuh - Amherst College - 2026 (Nick.Holschuh@gmail.com)
    % This function uses PyVista to initiate an interactive fence diagram
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % The inputs are:
    %
    % plotter - The Pyvista plotter object generated by "fence_initiate"
    % xlabel - Axis label for the x axis
    % ylabel - Axis label for the y axis
    % zlabel - Axis label for the vertical axis (doesn't seem to work?)
    %
    %%%%%%%%%%%%%%%
    % The output is a dictionary containing:
    %
    % plotter - The plotter object which can be passed into later functions
    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    """
    if plotter.scale[2] > 1:
        zlabel = 'Sacaled Vertical (%d x)' % plotter.scale[2]

    
    plotter.show_grid(
        xlabel=xlabel,
        ylabel=ylabel,
        zlabel=zlabel,
        font_size=14,
        color='black',       # Color of the text and grid lines
        location='outer',    # Keeps the labels on the outside of the 3D box
        grid=False           # Set to True if you want physical grid lines drawn inside the box
    )

    return plotter