import matplotlib.pyplot as plt
import numpy as np
import os

################## NDH Tools self imports
###########################################################
from .find_nearest import find_nearest
from .radar_load_music import radar_load_music
from .remove_image import remove_image
from .remove_line import remove_line
from .str_compare import str_compare
###########################################################

def generate_pickingpdf_fromlist_offnadir(fn_list,off_nadir_ind_spacing=8,picking_root_dir='./',clims=[]):
    """
    % (C) Nick Holschuh - Amherst College -- 2022 (Nick.Holschuh@gmail.com)
    %
    %     This function takes a music file or a directory of 
    %     standard files and generates a pdf with slices (or frames) that
    %     can be annotated by hand using GoodNotes6 on the iPad, and parsed
    %     using the process_XXXXX_pickedpdf.py scripts.
    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % The inputs are:
    %
    %     fnlist -- list of files to extract info from
    %
    %     picking_root_dir - In this directory, a folder called "to_pick" will get
    %                        generated that stores the new picking pdfs.
    %
    %
    %     clims - default=[], only implemented for standard images. Allows you to change
    %             the vmin and vmax for the image. Supply a two value list if desired.
    %
    %     alternative_data_opt - default=0. Some radar files generated by BAS or UTIG
    %                            have two different waveforms. Setting this flag to 1
    %                            will use the non-default waveform.
    %
    %%%%%%%%%%%%%%%
    % The outputs are:
    %
    %     This will write a picking pdf to the To_Pick folder of your choice.
    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    """ 

    ######### Set-up the directory where picks are placed
    if not os.path.isdir(picking_root_dir+'To_Pick'):
        os.makedirs(picking_root_dir+'To_Pick') 
    
    ######### Set-up the directory where picks are placed
    if not os.path.isdir(picking_root_dir+'To_Pick/list_of_frames'):
        os.makedirs(picking_root_dir+'To_Pick/list_of_frames') 
    
    fig = plt.figure(figsize=(15,10))                    
    ax = plt.gca()  
    
    num_to_remove = 0;
    
    for ind1,fn in enumerate(fn_list):
        try:
            radar_data = radar_load_music(fn)
        except:
            radar_data,depth_data = radar_load_music('')

        
            
        if len(radar_data.keys()) > 0:
            crop_string = 'nocrop'      
            off_nadir_inds = (radar_data['Tomo']['img'].shape[1]/2)+np.array([-off_nadir_ind_spacing,off_nadir_ind_spacing])
            off_nadir_inds = off_nadir_inds.astype(int)               
            remove_image(ax,1,verbose=0)
            remove_line(ax,num_to_remove,verbose=0)
            
            
            if len(clims) > 0:
               imdata = plt.imshow(np.sum(10*np.log10(radar_data['Tomo']['img'][:,off_nadir_inds,:]),axis=1),
                                   origin='lower',aspect='auto',cmap='gray_r',vmin=clims[0],vmax=clims[1])
            else:
               imdata = plt.imshow(np.sum(10*np.log10(radar_data['Tomo']['img'][:,off_nadir_inds,:]),axis=1),
                                   origin='lower',aspect='auto',cmap='gray_r')                 
            
            num_to_remove = len(radar_data['im_end'][1:])
               
        else:
            remove_image(ax,1,verbose=0)
            remove_line(ax,num_to_remove,verbose=0)
            plt.imshow([[1]],cmap='gray_r',vmin=0,vmax=5)
            num_to_remove = 0
            ax.set_xlim([-0.5,0.5])
            
        
        
        ax.set_aspect('auto')
        ax.invert_yaxis()
        plt.axis('off')
        
        frame_fn = '%s/To_Pick/list_of_frames/frame_%0.3d.png' %(picking_root_dir,ind1)
        plt.savefig(frame_fn)
        print('  --- Completed Image '+str(ind1)+' of '+str(len(fn_list)))

    
    print('Completed the image generation')
    
    ########## Website used to do the following:
    # https://stackoverflow.com/questions/9710118/convert-multipage-pdf-to-png-and-back-linux
    
    ########## This converts all the images to a single pdf
    pdfroot = picking_root_dir+'To_Pick/'
    pdfname=pdfroot+'ListedFrames.pdf'
    frames = '%s/To_Pick/list_of_frames/*.png' % (picking_root_dir)
    os.system("convert -adjoin "+frames+" -gravity center -scale '90<x770<' "+pdfname)
    ###########        
    



