import matplotlib.pyplot as plt
import numpy as np
import os


def generate_pickingpdf_fromlist(fn_list,picking_root_dir='./',clims=[], alternative_data_opt=0):
    """
    % (C) Nick Holschuh - Amherst College -- 2022 (Nick.Holschuh@gmail.com)
    %
    %     This function takes either a music file or a directory of 
    %     standard files and generates a pdf with slices (or frames) that
    %     can be annotated by hand using GoodNotes6 on the iPad, and parsed
    %     using the process_XXXXX_pickedpdf.py scripts.
    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % The inputs are:
    %
    %     fnlist -- list of files to extract info from
    %
    %     picking_root_dir - In this directory, a folder called "to_pick" will get
    %                        generated that stores the new picking pdfs.
    %
    %
    %     clims - default=[], only implemented for standard images. Allows you to change
    %             the vmin and vmax for the image. Supply a two value list if desired.
    %
    %     alternative_data_opt - default=0. Some radar files generated by BAS or UTIG
    %                            have two different waveforms. Setting this flag to 1
    %                            will use the non-default waveform.
    %
    %%%%%%%%%%%%%%%
    % The outputs are:
    %
    %     This will write a picking pdf to the To_Pick folder of your choice.
    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    """ 

    ######### Set-up the directory where picks are placed
    if not os.path.isdir(picking_root_dir+'To_Pick'):
        os.makedirs(picking_root_dir+'To_Pick') 

    ######### Set-up the directory where picks are placed
    if not os.path.isdir(picking_root_dir+'To_Pick/list_of_frames'):
        os.makedirs(picking_root_dir+'To_Pick/list_of_frames') 

    fig = plt.figure(figsize=(15,10))                    
    ax = plt.gca()  

    num_to_remove = 0;
    for ind1,fn in enumerate(fn_list):
        try:
            radar_data,depth_data = radar_load(fn,plot_flag=0,elevation1_or_depth2=0)
        except:
            radar_data,depth_data = radar_load('')
            
        if len(radar_data.keys()) > 0:
           bot_inds = find_nearest(radar_data['Time'],radar_data['Bottom'])['index'].astype(float)
           surf_inds = find_nearest(radar_data['Time'],radar_data['Surface'])['index'].astype(float)        
           bot_inds[bot_inds == 0] = np.nan
           surf_inds[surf_inds == 0] = np.nan
           bot_ind = len(radar_data['Time'])
           crop_string = 'nocrop'      
               
           remove_image(ax,1,verbose=0)
           remove_line(ax,num_to_remove,verbose=0)
            
           if np.isnan(bot_ind) == 1:
               plt.plot(0,0)
           else:
               ########### This accomodates files that have more than one data type
               if alternative_data_opt == 1:
                   find_data_opts = str_compare(radar_data.keys,'Data2')
                   if len(find_data_opts[0]) > 0:
                       radar_data['Data'] = radar_data['Data2']
               if len(clims) > 0:
                   imdata = plt.imshow(10*np.log10(radar_data['Data'][:int(bot_ind),:]),
                                       origin='lower',aspect='auto',cmap='gray_r',vmin=clims[0],vmax=clims[1])
               else:
                   imdata = plt.imshow(10*np.log10(radar_data['Data'][:int(bot_ind),:]),
                                       origin='lower',aspect='auto',cmap='gray_r')                 
        
        
           for hbar in radar_data['im_end'][1:]:
                plt.axvline(hbar,c='green',lw=1)
        
           num_to_remove = len(radar_data['im_end'][1:])
           ax.set_xlim([0,hbar])
               
        else:
            remove_image(ax,1,verbose=0)
            remove_line(ax,num_to_remove,verbose=0)
            plt.imshow([[1]],cmap='gray_r',vmin=0,vmax=5)
            num_to_remove = 0
            ax.set_xlim([-0.5,0.5])
            
        
        
        ax.set_aspect('auto')
        ax.invert_yaxis()
        plt.axis('off')
        
        frame_fn = '%s/To_Pick/list_of_frames/frame_%0.3d.png' %(picking_root_dir,ind1)
        plt.savefig(frame_fn)
        print('  --- Completed Image '+str(ind1)+' of '+str(len(fn_list)))
    

    print('Completed the image generation')
    
    ########## Website used to do the following:
    # https://stackoverflow.com/questions/9710118/convert-multipage-pdf-to-png-and-back-linux

    ########## This converts all the images to a single pdf
    pdfroot = picking_root_dir+'To_Pick/'
    pdfname=pdfroot+'ListedFrames.pdf'
    frames = '%s/To_Pick/list_of_frames/*.png' % (picking_root_dir)
    os.system("convert -adjoin "+frames+" -gravity center -scale '90<x770<' "+pdfname)
    ###########        





